#!/bin/zsh


directory="$HOME/.config/scripts"
script="$(ls $directory | choose -f "Operator Mono" -c "deaf9d" -b "1c1b1d")"
if [[ -n "$script" ]]; then
	file="$directory/$script"
	alacritty --command nvim "$file"
fi
