#!/usr/bin/env bash


choice="$(yabai -m query --windows | jq '.[] | .title + " " + (.id|tostring)' | choose -u -f "SF Mono" -c "c6eae6" -b "f7f1e3")"
win="$(echo $choice | tr -d '"' | awk '{print $NF}')"

yabai -m window --focus $win
