#!/bin/zsh


# get user selection
emoji=$(cut -d ';' -f1 ~/.config/emoji/emoji | choose -u -f "SF Mono" -c "c6eae6" -b "f7f1e3" | sed "s/ .*//")

# copy into clipboard
# copyq is used as pbcopy messes up the output when used from skhd for some reason
copyq copy $emoji
