#!/usr/bin/env bash


choice="$(echo -e "config\nscripts" | choose -f "Cartograph CF" -c "deaf9d" -b "1c1b1d")"

case "$choice" in
	config)
		declare options=("alacritty\nfirefox\nneovim\nskhd\nspacebar\nyabai\nzsh")

		config="$(echo -e "${options[@]}" | choose -f "Cartograph CF" -c "deaf9d" -b "1c1b1d")"

		case "$config" in
			quit)
				echo "Program terminated" && exit 1
			;;
			alacritty)
				file="$HOME/.config/alacritty/alacritty.yml"
			;;
			firefox)
				file="$HOME/Library/Application Support/Firefox/Profiles/fo46dfhz.default-release/chrome/userChrome.css"
			;;
			neovim)
				file="$HOME/.config/nvim/init.vim"
			;;
			skhd)
				file="$HOME/.config/skhd/skhdrc"
			;;
			spacebar)
				file="$HOME/.config/spacebar/spacebarrc"
			;;
			yabai)
				file="$HOME/.config/yabai/yabairc"
			;;
			zsh)
				file="$HOME/.config/zsh/.zshrc"
			;;
			script)
				script="on"
			;;
			*)
				exit 1
			;;
		esac
		alacritty --command nvim "$file"
	;;
	scripts)
		directory="$HOME/.config/scripts"
		script="$(ls $directory | choose -f "Cartograph CF" -c "deaf9d" -b "1c1b1d")"
		if [[ -n "$script" ]]; then
			file="$directory/$script"
			alacritty --command nvim "$file"
		fi
	;;
esac
