#!/usr/bin/env bash


if [[ $1 = "finder" ]]; then
	osascript <<-EOD
		tell application "Finder"
			set myW to make new Finder window
			set target of myW to home
			activate
			set toolbar visible of every Finder window to 1
			tell column view options of every Finder window
				set shows icon to true
				set shows icon preview to true
				set shows preview column to true
				set discloses preview pane to true
			end tell
		end tell
	EOD
else
	directory="/Applications ~/Applications"
	app="$(ls $directory | grep -v / | grep .app | sed -e 's/\.app$//' | choose -f "Operator Mono" -c "deaf9d")"
	open -a $app
fi

