#!/usr/bin/env bash


input="$(echo -e "Search DuckDuckGo" | choose -f "Operator Mono" -c "deaf9d" -b "1c1b1d" -m)"
search=${input// /+} # replace whitespace with a '+'
if [[ -n "$search" ]]; then
	open "https://duckduckgo.com/?t=ffab&q=$search"
fi
