#!/usr/bin/env bash

dir="$HOME/Pictures/Screenshots/$(date +'%F')"
file="$(date +'%H-%M-%S')"
image="$dir/$file.png"

screenshot() {
	mkdir -p "$dir"
	if [[ "$interactive" ]] ; then
		screencapture -ic "$image"
	else
		screencapture -Sc "$image"
        fi
	pngpaste "$image"
}

flags() {
	while getopts ih opt; do
		case $opt in
			i) interactive="on"
			;;
			h) echo "-s to capture whole screen"
			;;
			*) echo "-s to capture whole screen"
			;;
		esac
	done
}

if [ "$#" -ne 0 ]; then
	flags "$@"
	screenshot
else
	screenshot
fi
