#!/usr/bin/env bash


# current_padding = $(yabai -m config window_gap)
# declare -i current_padding

ps cax | grep sketchybar > /dev/null
if [ $? -eq 0 ] ; then
	launchctl unload /usr/local/opt/sketchybar/homebrew.mxcl.sketchybar.plist
	sketchybar -m --bar --hidden=on
	yabai -m config external_bar all:0:0
else
	launchctl load /usr/local/opt/sketchybar/homebrew.mxcl.sketchybar.plist
	sketchybar -m --bar --hidden=off
	yabai -m config external_bar all:45:0
fi

