export ZDOTDIR=$HOME/.config/zsh
export GOPATH=$HOME/Library/go
export PYTHONSTARTUP=$HOME/.config/python/.pythonrc
export PYLINTHOME=$HOME/.config/python/pylint
export GNUPGHOME=$HOME/.config/gnupg
export PYENV_ROOT=$HOME/.config/pyenv
export IPYTHONDIR=$HOME/.config/iPython
export NPM_CONFIG_USERCONFIG=$HOME/.config/npm/.npmrc
export SPICETIFY_CONFIG=$HOME/.config/spicetify
export LESSHISTFILE=$HOME/.cache/less/lesshst
export SQLITE_HISTORY=$HOME/.cache/sqlite_history
export GNUPGHOME=$HOME/.local/share/gnupg
export VISUAL=hx
export EDITOR=$VISUAL
export RANGER_LOAD_DEFAULT_RC=FALSE
export BW_SESSION="6cAZEigtEVSWDWDIzcjKcbpL16Gyg1TwGdaLuAD1xNLIGF5itecXzBBafcVEYDf7eD6HWgbqkLmp8sVyRm7G0Q=="
export HOMEBREW_NO_INSTALL_FROM_API=1
export CARGO_HOME=$HOME/.config/cargo
export RUSTUP_HOME=$HOME/.config/rustup
export PATH="$HOME/.config/cargo/bin:$HOME/.config/scripts:$HOME/.local/bin:/opt/homebrew/opt/llvm/bin:$PATH"

source "$HOME/.config/cargo/env"
