#!/usr/bin/env sh

# start yabai
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_opacity off
yabai -m config window_shadow off
yabai -m config window_animation_duration 0.1
yabai -m config window_border_hidpi on
yabai -m config window_origin_display focused
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack

# borders
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_border_radius 12
yabai -m config active_window_border_color 0xff191724
yabai -m config normal_window_border_color 0xfffaf4ed

# layouts
yabai -m config --space 1 layout stack
yabai -m config --space 4 layout stack
yabai -m config --space 5 layout stack

# rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Roblox$" manage=off border=off
yabai -m rule --add app="^csgo_osx64$" border=off
yabai -m rule --add app="^Firefox$" space=1
yabai -m rule --add app="^Spotify$" space=4
yabai -m rule --add app="^Mail$" space=4
yabai -m rule --add app="^ProtonVPN$" space=4
yabai -m rule --add app="^Discord" space=5
yabai -m rule --add app="^eqMac$" manage=off
yabai -m rule --add app="^Windscribe$" manage=off border=off

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# bar
if pgrep sketchybar; then
	launchctl load /Users/cobcob/Library/LaunchAgents/homebrew.mxcl.sketchybar.plist
	bar_offset=$(sketchybar --query bar | jq '.y_offset')
    bar_height=$(sketchybar --query bar | jq '.height')
	y_offset=$((bar_offset + bar_height))
	yabai -m config external_bar all:$y_offset:0
else
	launchctl unload /Users/cobcob/Library/LaunchAgents/homebrew.mxcl.sketchybar.plist
	yabai -m config external_bar all:0:0
fi

# signals
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

# autoupdate
YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

# hash
yabai_hash &
