inherits = "rose_pine_dawn"

"variable.parameter" = { fg = "iris", modifiers = ["italic"] }
"variable.other.member" = { fg = "iris", modifiers = ["italic"] }
"keyword.control" = { fg = "pine", modifiers = ["italic"] }

"ui.virtual.inlay-hint" = { fg = "gold" }