# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1c1b1d'
foreground='#deaf9d'
cursor='#fafafa'

# Colors
color0='#1f1e20'
color1='#aa2f3b'
color2='#c6c5bf'
color3='#e5d4aa'
color4='#737174'
color5='#747271'
color6='#62605f'
color7='#f2efed'
color8='#505354'
color9='#e03d4e'
color10='#c6c5bf'
color11='#e6ce92'
color12='#919495'
color13='#9a9a9d'
color14='#a3a3a6'
color15='#dadbd6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
