#!/usr/bin/env bash


# import colors
. "${HOME}/.cache/wal/colors.sh"

# plugin directory variable
PLUGINS_DIR="$HOME/.config/sketchybar/plugins"

# set bar
sketchybar -m --bar height=40                                                                                \
                    position=top                                                                             \
                    margin=10                                                                                \
                    corner_radius=10                                                                         \
                    y_offset=10                                                                              \
                    padding_left=10                                                                          \
                    padding_right=11                                                                         \
                    topmost=off                                                                              \
                    hidden=off                                                                               \
                    color=0xfff7f1e3                                                                         \
                    border_color=0xff211a15                                                                  \
                    border_width=3                                                                           \
                    font_smoothing=on                                                                        \
                    # blur_radius=50                                                                           \

# global defaults
sketchybar -m --default drawing=on                                                                           \
                        y_offset=0                                                                           \

# label defaults
sketchybar -m --default label.color=0xff211a15                                                               \
                        label.font="SF Pro Text:Bold:14.0"                                                   \
                        label.highlight_color=0xff6b675c                                                     \
                        label.padding_left=0                                                                 \
                        label.padding_right=0                                                                \

# icon defaults
sketchybar -m --default icon.color=0xff211a15                                                                \
                        icon.font="Hack Nerd Font:Bold:16.0"                                                 \
                        icon.highlight_color=0xff6b675c                                                      \
                        icon.padding_left=0                                                                  \
                        icon.padding_right=0                                                                 \

# background defaults
sketchybar -m --default background.border_color=0xff"${color7//#}"                                           \
                        background.border_width=0                                                            \
                        background.corner_radius=10                                                          \
                        background.height=30                                                                 \

# popup defaults
sketchybar -m --default popup.background.corner_radius=10                                                    \
                        popup.background.border_width=3                                                      \
                        popup.background.border_color=0xff211a15                                             \
                        popup.background.color=0xfff7f1e3                                                    \
                        popup.y_offset=5                                                                     \

# events
# sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged"
sketchybar -m --add event window_focus
sketchybar -m --add event title_change

# spotify
sketchybar -m --add item spotify left                                                                        \
              --set spotify                                                                                  \
                    icon=                                                                                   \
                    icon.padding_left=10                                                                     \
                    icon.padding_right=40                                                                    \
                    popup.horizontal=on                                                                      \
                    click_script="sketchybar -m --set \$NAME popup.drawing=toggle"                           \

sketchybar -m --add item rewind popup.spotify                                                                \
              --set rewind                                                                                   \
                    icon=􀊎                                                                                   \
                    icon.padding_left=10                                                                     \
                    icon.padding_right=14                                                                    \
                    click_script="osascript -e 'tell application \"Spotify\" to play previous track' ;
                    sketchybar -m --set spotify popup.drawing=off"                                           \

sketchybar -m --add item playpause popup.spotify                                                             \
              --set playpause                                                                                \
                    icon.padding_right=10                                                                    \
                    script="$PLUGINS_DIR/spotifyIndicator.sh"                                                \
                    click_script="osascript -e 'tell application \"Spotify\" to playpause' ;
                                  sketchybar -m --set spotify popup.drawing=off ;
                                  $PLUGINS_DIR/spotifyIndicator.sh"                                          \

sketchybar -m --add item skip popup.spotify                                                                  \
              --set skip                                                                                     \
                    icon=􀊐                                                                                   \
                    icon.padding_right=14                                                                    \
                    click_script="osascript -e 'tell application \"Spotify\" to play next track' ;
                                  sketchybar -m --set spotify popup.drawing=off"                             \

# spaces
sketchybar -m --add space browser left                                                                       \
              --set browser                                                                                  \
                    associated_space=1                                                                       \
                    associated_display=1                                                                     \
                    icon=""                                                                                 \
                    icon.padding_right=12                                                                    \
                    icon.font="Hack Nerd Font:Bold:14.0"                                                     \
                    script="$PLUGINS_DIR/space.sh"                                                           \
                    click_script="yabai -m space --focus 1"                                                  \

sketchybar -m --add space terminal left                                                                      \
              --set terminal                                                                                 \
                    associated_space=2                                                                       \
                    associated_display=1                                                                     \
                    icon=""                                                                                 \
                    icon.padding_right=12                                                                    \
                    icon.font="Hack Nerd Font:Bold:18.0"                                                     \
                    script="$PLUGINS_DIR/space.sh"                                                           \
                    click_script="yabai -m space --focus 2"                                                  \


sketchybar -m --add space files left                                                                         \
              --set files                                                                                    \
                    associated_space=3                                                                       \
                    associated_display=1                                                                     \
                    icon=""                                                                                 \
                    icon.padding_left=1                                                                      \
                    icon.padding_right=12                                                                    \
                    script="$PLUGINS_DIR/space.sh"                                                           \
                    click_script="yabai -m space --focus 3"                                                  \

sketchybar -m --add space music left                                                                         \
              --set music                                                                                    \
                    associated_space=4                                                                       \
                    associated_display=1                                                                     \
                    icon=""                                                                                 \
                    icon.padding_right=12                                                                    \
                    script="$PLUGINS_DIR/space.sh"                                                           \
                    click_script="yabai -m space --focus 4"                                                  \

sketchybar -m --add space chat left                                                                          \
              --set chat                                                                                     \
                    associated_space=5                                                                       \
                    associated_display=1                                                                     \
                    icon="ﭮ"                                                                                 \
                    icon.padding_right=4                                                                     \
                    script="$PLUGINS_DIR/space.sh"                                                           \
                    click_script="yabai -m space --focus 5"                                                  \

# title
sketchybar -m --add item title center                                                                        \
              --set title                                                                                    \
                    icon=""                                                                                  \
                    icon.color=0xFF"${cursor//#}"                                                            \
                    icon.padding_left=8                                                                      \
                    icon.padding_right=0                                                                     \
                    label.padding_right=11                                                                   \
                    script="$PLUGINS_DIR/window_title.sh"                                                    \
                    click_script=opener                                                                      \
               --subscribe title                                                                             \
                    window_focus                                                                             \
                    front_app_switched                                                                       \
                    space_change                                                                             \
                    title_change                                                                             \

# time, date, and battery
sketchybar -m --add item time right                                                                          \
              --set time                                                                                     \
                    update_freq=5                                                                            \
                    label.padding_right=10                                                                   \
                    popup.align=center                                                                       \
                    script="$PLUGINS_DIR/clock.sh"                                                           \
                    click_script="sketchybar -m --set time popup.drawing=toggle"                             \

sketchybar -m --add item date popup.time                                                                     \
              --set date                                                                                     \
                    label.padding_left=10                                                                    \
                    label.padding_right=10                                                                   \
                    script="$PLUGINS_DIR/date.sh"                                                            \

sketchybar -m --add item battery popup.time                                                                  \
              --set battery                                                                                  \
                    icon.padding_left=10                                                                     \
                    label.padding_left=5                                                                     \
                    label.padding_right=10                                                                   \
                    script="$PLUGINS_DIR/power.sh"                                                           \

# load
sketchybar -m --update

echo "sketchybar configuration loaded.."

