theme = "rose_pine_dawn"

[editor]
# line-number = "relative"
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
gutters = ["diagnostics", "spacer", "diff"]
idle-timeout = 0
mouse = true
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[keys.normal]
";" = "command_mode"
"esc" = ["collapse_selection", "keep_primary_selection"]
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
X = "extend_line_above"
d = ["yank_joined_to_clipboard", "delete_selection"]
p = "paste_clipboard_after"
y = "yank_joined_to_clipboard"

[keys.select]
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
X = "extend_line_above"
d = ["yank_joined_to_clipboard", "delete_selection"]
p = "paste_clipboard_after"
y = "yank_joined_to_clipboard"
