theme = "rose_pine_personal"

[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
completion-trigger-len = 1
gutters = ["diagnostics", "spacer", "diff"]
idle-timeout = 0
mouse = true
soft-wrap.enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true

[keys.normal]
";" = "command_mode"
"esc" = ["collapse_selection", "keep_primary_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
X = "extend_line_above"
d = ["yank_joined_to_clipboard", "delete_selection"]
p = "paste_clipboard_after"
u = ["undo", "collapse_selection"]
y = "yank_joined_to_clipboard"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
X = "extend_line_above"
d = ["yank_joined_to_clipboard", "delete_selection"]
p = "paste_clipboard_after"
y = "yank_joined_to_clipboard"
