[[language]]
name = "cpp"
auto-format = true
language-server = {command = "clangd", args = ["--fallback-style=Google"]}

[[language]]
name = "c"
auto-format = true
language-server = {command = "clangd", args = ["--fallback-style=Google"]}

[[language]]
name = "python"
auto-format = true

[[language]]
name = "latex"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language.config.texlab.forwardSearch]
executable = "sioyek"
args = [ "--forward-search-file", "%f", "--forward-search-line", "%l", "%p" ]

[language.config.texlab.chktex]
onEdit = true

[[language]]
name = "markdown"
file-types = [ "md", "markdown" ]
language-server = { command = "mdpls" }
config = { markdown.preview.auto = true, markdown.preview.codeTheme = "base16/ros-pine-dawn" }
