[language-server.clangd]
command = "clangd"
args = [ "--fallback-style=Google" ]

[language-server.mdpls]
command = "mdpls"
config = { markdown.preview.auto = true, markdown.preview.codeTheme = "base16/ros-pine-dawn" }

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab]
build = { onSave = true, forwardSearchAfter = true }
forwardSearch = { executable = "sioyek", args = [ "--forward-search-file", "%f", "--forward-search-line", "%l", "%p" ] }
chktex = {onEdit = true }

[[language]]
name = "cpp"
auto-format = true
language-servers = [ "clangd" ]

[[language]]
name = "c"
auto-format = true
language-servers = [ "clangd" ]

[[language]]
name = "python"
auto-format = true

[[language]]
name = "latex"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "texlab" ]

[[language]]
name = "markdown"
file-types = [ "md", "markdown" ]
language-servers = [ "mdpls" ]
